jobs:
  build:
    docker:
      - image: python:3.6                   # similar to "image" in GitLab
    steps:
      - checkout
      - run: |                              # similar to "script" in GitLab
          pip install -r requirements.txt
          python manage.py check

  test:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: |
          pip install -r requirements.txt
          python manage.py test taskManager

  sast:
    machine: true
    steps:
      - checkout

      - run: |
          docker run --rm -v $(pwd):/src hysnsec/bandit -r /src -f json -o /src/bandit-output.json
          when: on_fail

      - store_artifacts:
          path: bandit-output.json
          destination: bandit-artifact
          when: always

  secret_scanning:
    machine: true
    steps:
      - checkout

      - run: |
          docker run --rm -v $(pwd):/src hysnsec/trufflehog file:///src --json > trufflehog-output.json
          when: on_fail

      - store_artifacts:
          path: trufflehog-output.json
          destination: trufflehog-artifact
          when: always

  oast:
    machine: true
    steps:
      - checkout

      - run: |
          docker run -v $(pwd):/src --rm hysnsec/safety check -r requirements.txt --json | tee oast-results.json
          when: on_fail             # Even if the job fails, continue to the next stages

      - store_artifacts:
          path: oast-results.json
          destination: safety-artifact
          when: always

  oast-frontend:
    docker:
      - image: node:alpine3.10
    steps:
      - checkout
      - run: | 
          npm install
          npm install -g retire
          retire --severity high --outputformat json --outputpath retirejs-report.json
          when: on_fail

      - store_artifacts:
          path: retirejs-report.json
          destination: retirejs-artifact
          when: always 

  oast-snyk:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: |
          wget -O snyk https://github.com/snyk/snyk/releases/download/v1.573.0/snyk-linux
          chmod +x snyk
          mv snyk /usr/local/bin/
          npm install
          snyk test --json > snyk-results.json
          when: on_fail

      - store_artifacts:
          path: snyk-results.json
          destination: snyk-artifact
          when: always


  zap_baseline:
    machine: true
    steps:
      - checkout

      - run: |
          docker pull owasp/zap2docker-stable:2.10.0
          docker run --user root --rm -v $(pwd):/zap/wrk:rw -w /zap owasp/zap2docker-stable:2.10.0 zap-baseline.py -t ${PROD_URL} -J zap-output.json

      - store_artifacts:
          path: zap-output.json
          destination: zap-artifact
          when: always

  integration:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          command: |
            echo "This is an integration step"
            exit 1
          when: on_fail                    # Even if the job fails, continue to the next stages

  prod:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: echo "This is a deploy step"

workflows:
  version: 2
  django:
    jobs:
      - build
      - test:
          requires:
            - build
      - sast:
          requires:
            - build
      - secret_scanning:
          requires:
            - test
      - oast:
          requires:
            - test
      - oast-frontend:
          requires:
            - test
      - oast-snyk:
          requires:
            - test
      - zap_baseline:
          requires:
            - test
      - integration:
          requires:
            - oast
      - prod:
          type: approval
          requires:
            - integration
