jobs:
  build:
    docker:
      - image: python:3.6                   # similar to "image" in GitLab
    steps:
      - checkout
      - run: |                              # similar to "script" in GitLab
          pip install -r requirements.txt
          python manage.py check

  test:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: |
          pip install -r requirements.txt
          python manage.py test taskManager

  oast:
    machine: true
    steps:
      - checkout

      - run:
          command: docker run -v $(pwd):/src --rm hysnsec/safety check -r requirements.txt --json | tee oast-results.json
          when: on_fail             # Even if the job fails, continue to the next stages

      - store_artifacts:
          path: oast-results.json
          destination: safety-artifact
          when: always

          #  oast-frontend:
          #    docker:
          #      - image: node:alpine3.10
          #    steps:
          #      - checkout
          #      - run: |
          #          npm install
          #          npm install -g retire
          #          retire --severity high --outputformat json --outputpath retirejs-report.json

          #      - store_artifacts:
          #          path: retirejs-report.json
          #          destination: retirejs-artifact
          #          when: always 


  oast-frontend:
    machine: true
    steps:
      - checkout

      - run: docker run --rm -v $(pwd):/src -w /src hysnsec/retire --outputformat json --outputpath retirejs-output2.json --severity high

      - store_artifacts:
          path: retirejs-output2.json
          destination: retirejs-artifact

  integration:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          command: |
            echo "This is an integration step"
            exit 1
          when: on_fail                    # Even if the job fails, continue to the next stages

  prod:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: echo "This is a deploy step"

workflows:
  version: 2
  django:
    jobs:
      - build
      - test:
          requires:
            - build
      - oast:
          requires:
            - test
      - oast-frontend:
          requires:
            - test
      - integration:
          requires:
            - oast
      - prod:
          type: approval
          requires:
            - integration
